#!/bin/sh
set -e

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp

echo
echo "Welcome to Jenteck OS"
echo "Kernel: $(uname -r)"

if [ -x /bin/sh ]; then
  exec /bin/sh
else
  echo "No shell available. Dropping to busybox ash if installed."
  exec /bin/ash
fi
